# Generated by Django 5.1.2 on 2024-11-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email_adress', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('lecture_material', models.FileField(blank=True, max_length=255, upload_to='')),
                ('past_question', models.FileField(blank=True, max_length=255, upload_to='')),
            ],
        ),
    ]
