# Generated by Django 5.1.2 on 2024-11-06 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudyBetter', '0002_rename_users_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='lecture_material',
        ),
        migrations.RemoveField(
            model_name='user',
            name='past_question',
        ),
    ]
