# Generated by Django 5.1.2 on 2024-11-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyBetter', '0003_remove_user_lecture_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirm_password',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
