# Generated by Django 5.1.2 on 2024-11-06 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudyBetter', '0004_user_confirm_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_adress',
            new_name='email',
        ),
    ]
