# Generated by Django 5.1.2 on 2024-11-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyBetter', '0005_rename_email_adress_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
