# Generated by Django 5.1.2 on 2024-11-09 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudyBetter', '0006_alter_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
